version: '3'
services:
  terraform:
    hostname: provbee
    container_name: provbee
    image: nexclipper/provbee
#    restart: always
    volumes:
#      - ./zzz:/data
      - /root/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZZZ=ZZZ
#      - TERRAVERSION=0.12.18
#      - KUCTLVERSION=v1.18.4
#      - HELMVERSION=v3.2.1
#    command: tail -F anything
