apiVersion: v1
kind: Service
metadata:
  name: provbee-service
  namespace: ${KUBENAMESPACE}
spec:
  selector:
    name: provbee
  clusterIP: None
  ports:
  - name: provbee # Actually, no port is needed.
    port: 22
    targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${KUBENAMESPACE}
  name: provbee
  labels:
    name: provbee
spec:
  selector:
    matchLabels:
      name: provbee
  template:
    metadata:
      labels:
        name: provbee
    spec:
      serviceAccountName: ${KUBESERVICEACCOUNT}
      containers:
      - name: provbee
        image: nexclipper/provbee:${TAGPROV}
        command: ['bash', '-c', '/entrypoint.sh']
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: ssh-auth
          mountPath: /data/.provbee/
        - name: kube-config
          mountPath: /root/.kube/
      volumes:
      - name: ssh-auth
        secret:
          secretName: ${KUBESERVICEACCOUNT}-ssh-key
    #      defaultMode: 0644
          items:
          - key: pubkey
            path: configmap_authkey
      - name: kube-config
        secret:
          secretName: ${KUBESERVICEACCOUNT}-kubeconfig
          defaultMode: 0644
          items:
          - key: kubeconfig
            path: config
            
