#apiVersion: v1
#kind: Service
#metadata:
#  name: webstork-service
#  namespace: ${KUBENAMESPACE}
#spec:
#  selector:
#    name: webstork
#  clusterIP: None
#  ports:
#  - name: webstork # Actually, no port is needed.
#    port: 8282
#    targetPort: 80
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${KUBENAMESPACE}
  name: webstork
  labels:
    name: webstork
spec:
  selector:
    matchLabels:
      name: webstork
  template:
    metadata:
      labels:
        name: webstork
    spec:
      serviceAccountName: ${KUBESERVICEACCOUNT}
      containers:
      - name: webstork
        image: nexclipper/webstork:latest
        command: ['sh', '-c', '/entrypoint.sh']
#        command: ['/usr/bin/tail', '-f', '/tmp/webstork_portforward.log']
#        resources:
#          requests:
#            memory: "128Mi"
#            cpu: "250m"
#          limits:
#            memory: "256Mi"
#            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 
          initialDelaySeconds: 5
