apiVersion: v1
kind: Service
metadata:
  name: webstork-service
  namespace: ${KUBENAMESPACE}
spec:
  selector:
    name: webstork
  clusterIP: None
  ports:
  - name: provbee # Actually, no port is needed.
    port: 8282
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${KUBENAMESPACE}
  name: webstork
  labels:
    name: webstork
spec:
  selector:
    matchLabels:
      name: webstork
  template:
    metadata:
      labels:
        name: webstork
    spec:
      serviceAccountName: ${KUBESERVICEACCOUNT}
      containers:
      - name: webstork
        image: nexclipper/webstork:latest
        command: ['sh', '-c', 'echo zzz && sleep 6000']
#        resources:
#          requests:
#            memory: "128Mi"
#            cpu: "250m"
#          limits:
#            memory: "256Mi"
#            cpu: "500m"
        volumeMounts:
        - name: ssh-auth
          mountPath: /data/.webstork/
        - name: kube-config
          mountPath: /root/.kube/
      volumes:
      - name: ssh-auth
        secret:
          secretName: ${KUBESERVICEACCOUNT}-ssh-key
    #      defaultMode: 0644
          items:
          - key: pubkey
            path: configmap_authkey
      - name: kube-config
        secret:
          secretName: ${KUBESERVICEACCOUNT}-kubeconfig
          defaultMode: 0644
          items:
          - key: kubeconfig
            path: config
