#apiVersion: v1
#kind: Service
#metadata:
#  name: webstork-service
#  namespace: ${KUBENAMESPACE}
#spec:
#  selector:
#    name: webstork
#  clusterIP: None
#  ports:
#  - name: webstork # Actually, no port is needed.
#    port: 8282
#    targetPort: 80
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${KUBENAMESPACE}
  name: webstork
  labels:
    name: webstork
spec:
  selector:
    matchLabels:
      name: webstork
  template:
    metadata:
      labels:
        name: webstork
    spec:
      serviceAccountName: ${KUBESERVICEACCOUNT}
      containers:
      - name: webstork
        image: nexclipper/webstork:latest
        command: ['sh', '-c', '/entrypoint.sh']
#        command: ['/usr/bin/tail', '-f', '/tmp/webstork_portforward.log']
#        resources:
#          requests:
#            memory: "128Mi"
#            cpu: "250m"
#          limits:
#            memory: "256Mi"
#            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricops
  namespace: nex-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricops
  template:
    metadata:
      labels:
        app: metricops
    spec:
      serviceAccountName: nexc
      containers:
      - image: nexclipper/metric-operator:0.2.0
        imagePullPolicy: IfNotPresent 
        name: metricops
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /redis-master-data             
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: metricops
  namespace: nex-system
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: metricops
