apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${KUBENAMESPACE}
  name: webstork
  labels:
    name: webstork
spec:
  selector:
    matchLabels:
      name: webstork
  template:
    metadata:
      labels:
        name: webstork
    spec:
      serviceAccountName: ${KUBESERVICEACCOUNT}
      containers:
      - name: webstork
        image: public.ecr.aws/nexclipper/webstork:nginx-alpine
        #imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
#        resources:
#          requests:
#            memory: "128Mi"
#            cpu: "250m"
#          limits:
#            memory: "256Mi"
#            cpu: "500m"
        ports:
        - containerPort: 8081 #alertmanager
        - containerPort: 80 #grafana
        - containerPort: 8282 #metricark
        - containerPort: 9090 #prometheus
        - containerPort: 8080 #promlens
        - containerPort: 9201 #promscale
        - containerPort: 9091 #pushgateway
        - containerPort: 30003 #test
      